[build]
  base = "apps/web"             # where package.json lives
  command = "npm run build"     # or: "npm ci && npm run build"
  publish = "apps/web/.next"    # for Next.js builds

# Remove the old pinned plugin (let Netlify install the latest automatically)
# [[plugins]]
#   package = "@netlify/plugin-nextjs"[build]
command = "npm run build"
publish = ".next"

[[headers]]
for = "/*"
  [headers.values]
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"

[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-ghost-inspector"

# Uncomment if you want Cloudflare purge once env vars are set
# [[plugins]]
# package = "netlify-purge-cloudflare-on-deploy"
