[build]
command = "npm ci && npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "20"

[[headers]]
for = "/*"
  [headers.values]
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"

[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Let Netlify manage the Next.js plugin from the UI — do not pin it here
# [[plugins]]
# package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-ghost-inspector"

# Optional: Cloudflare purge once env vars are set
# [[plugins]]
# package = "netlify-purge-cloudflare-on-deploy"
