[build]
command = "npm run build"
publish = ".next"

[[headers]]
for = "/*"
  [headers.values]
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"

[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-ghost-inspector"

# Uncomment if you want Cloudflare purge once env vars are set
# [[plugins]]
# package = "netlify-purge-cloudflare-on-deploy"
