[build]
  publish = "./"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-s3","@aws-sdk/s3-request-presigner","uuid"]

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
