[build]
  command = ""         # no build step
  publish = "."        # serve files from repo root

# optional security headers
[[headers]]
  for = "/*"
  [headers.values]
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
